name: Publish Docker image
on:
  push:
  schedule:
    - cron: "0 0 * * 0" # Execute this job every week

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: thomaslachaux/nginx-styled
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          tags: latest
